#!/usr/bin/env python

# Copyright 2017 Open Source Robotics Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import rospy
from uv_base.msg import Control
from sensor_msgs.msg import Joy
from geometry_msgs.msg import Twist
from mavros_msgs.msg import State
#######################################
## Logitech G920 with Pedal and Shift

# Steering
STEERING_AXIS = 0   # left 1 --> center 0 --> right -1

# Speed control
BUTTON_A = 0        # speed step down
BUTTON_B = 1        # steering step up
BUTTON_X = 2        # steering step down
BUTTON_Y = 3        # speed step up


# Throttle and Brake
THROTTLE_AXIS = 1   # release -1 --> press 1
BRAKE_AXIS = 2      # release -1 --> press 1
BRAKE_POINT = -0.9  # consider brake is applied if value is greater than this.

# Gear shift
# to be neutral, bothe SHIFT_FORWARD & SHIFT_REVERSE must be 0
SHIFT_FORWARD = 4     # forward 1
SHIFT_REVERSE = 5     # reverse 1

# Max speed and steering factor
MAX_THROTTLE_FACTOR = 30
MAX_STEERING_FACTOR = 10
# Default speed and steering factor
INIT_THROTTLE_FACTOR = 3
INIT_STERRING_FACTOR = 1

# Small value
SMALL_VALUE = 0.0001

class Translator:
    def __init__(self):
        self.sub = rospy.Subscriber("joy", Joy, self.callback)
        self.sub = rospy.Subscriber("mavros/state", State, self.mavstateCB )
        self.pub = rospy.Publisher('rover', Control, queue_size=20)
        # self.pub4mavros = rospy.Publisher('rover_vel', Twist, queue_size=20)
        self.pub4mavros = rospy.Publisher('mavros/setpoint_velocity/cmd_vel_unstamped', Twist, queue_size=20)

        self.last_published_time = rospy.get_rostime()
        self.last_published = None
        self.timer = rospy.Timer(rospy.Duration(1./20.), self.timer_callback)

        self.throttle_factor = INIT_THROTTLE_FACTOR
        self.steering_factor = INIT_STERRING_FACTOR
        
        self.msg_mav_state = State()
        self.gear = Control()
        self.gear_trigger = True
        
    def timer_callback(self, event):
        if self.last_published and self.last_published_time < rospy.get_rostime() + rospy.Duration(1.0/20.):
            self.callback(self.last_published)
    def mavstateCB(self, msg):
        self.msg_mav_state.armed = msg.armed
        
    def callback(self, message):
        rospy.logdebug("joy_translater received axes %s",message.axes)
        command = Control()
        command.header = message.header

        # Throttle speed control
        if message.buttons[BUTTON_Y] == 1:
            self.throttle_factor = self.throttle_factor + 1 if self.throttle_factor < MAX_THROTTLE_FACTOR else MAX_THROTTLE_FACTOR
        if message.buttons[BUTTON_A] == 1:
            self.throttle_factor = self.throttle_factor - 1 if self.throttle_factor > 1 else 1

        # Steering speed control
        if message.buttons[BUTTON_B] == 1:
            self.steering_factor = self.steering_factor + 1 if self.steering_factor < MAX_STEERING_FACTOR else MAX_STEERING_FACTOR
        if message.buttons[BUTTON_X] == 1:
            self.steering_factor = self.steering_factor - 1 if self.steering_factor > 1 else 1

        if message.axes[BRAKE_AXIS] > BRAKE_POINT:
            command.brake = 1.0
        # Note: init value of axes are all zeros
        # --> problem with -1 to 1 range values like brake
        if message.axes[BRAKE_AXIS] > -1*SMALL_VALUE and message.axes[BRAKE_AXIS] < SMALL_VALUE:
            command.brake = 0.0

        if message.axes[THROTTLE_AXIS] >= 0:
            command.throttle = message.axes[THROTTLE_AXIS]
            command.brake = 0.0
        else:
            command.throttle = 0.0
         #   command.brake = message.axes[THROTTLE_AXIS] * -1
          #  command.throttle = 0.0
        
        if message.buttons[SHIFT_FORWARD] == 1:
            if self.gear_trigger == True:
                rospy.loginfo("FORWARD")
                self.gear_trigger = False
            command.shift_gears = Control.FORWARD
            self.gear.shift_gears = command.shift_gears
        elif message.buttons[SHIFT_REVERSE] == 1:
            if self.gear_trigger == False:
                rospy.loginfo("REVERSE")
                self.gear_trigger = True
            command.shift_gears = Control.REVERSE
            self.gear.shift_gears = command.shift_gears
        elif message.buttons[SHIFT_FORWARD] == 1 and message.buttons[SHIFT_REVERSE] == 1 :
            rospy.loginfo("NO_COMMAND")
            command.shift_gears = Control.NO_COMMAND
            self.gear.shift_gears = command.shift_gears
        else:
            pass
            # command.shift_gears = Control.NO_COMMAND

        command.steer = message.axes[STEERING_AXIS]

        command4mavros = Twist()
        
        if self.msg_mav_state.armed == True:
            if self.gear.shift_gears == Control.FORWARD:
                command4mavros.linear.x = command.throttle*(1+self.throttle_factor)
                command4mavros.angular.z = command.steer*(1+self.steering_factor*0.5)
                self.pub4mavros.publish(command4mavros)
            elif self.gear.shift_gears == Control.REVERSE:
                command4mavros.linear.x = -command.throttle*(1+self.throttle_factor*0.1)
                command4mavros.angular.z = command.steer*(1+self.steering_factor*0.1)
                self.pub4mavros.publish(command4mavros)
            else:
                command4mavros.linear.x = 0
                command4mavros.angular.z = 0
                self.pub4mavros.publish(command4mavros)
        
        self.last_published = message
        self.pub.publish(command)

if __name__ == '__main__':
    rospy.init_node('joystick_control_node')
    t = Translator()
    rospy.spin()