#!/usr/bin/env python

import datetime
import os
import cv2
import time
import rospy
import numpy as np
from uv_base.msg import Control
from std_msgs.msg import Int32
from sensor_msgs.msg import Image
from geometry_msgs.msg import Twist

import sys

sys.path.append('../config/neural_net/')

import const
from image_converter import ImageConverter
from drive_run import DriveRun
from config import Config
from image_process import ImageProcess


class NeuralControl:
    def __init__(self, weight_file_name, default_speed):
        rospy.init_node('run_neural_node')
        self.ic = ImageConverter()
        self.image_process = ImageProcess()
        self.rate = rospy.Rate(30)
        self.drive= DriveRun(weight_file_name)
        rospy.Subscriber('/camera/image_raw', Image, self.controller_cb)
        rospy.Subscriber('rover_vel', Twist, self.rovervelCB )
        self.image = None
        self.image_processed = False
        self.config = Config()
        self.default_speed = default_speed

    def controller_cb(self, image): 
        img = self.ic.imgmsg_to_opencv(image)
        cropped = img[const.CROP_Y1:const.CROP_Y2,
                      const.CROP_X1:const.CROP_X2]

        img = cv2.resize(cropped,(const.IMAGE_WIDTH, const.IMAGE_HEIGHT))

        self.image = self.image_process.process(img)

        if self.config.net_model_type == const.NET_TYPE_LSTM_FC6 \
            or self.config.net_model_type == const.NET_TYPE_LSTM_FC7:
            self.image = np.array(self.image).reshape(1, self.config.image_size[1],
                                                         self.config.image_size[0],
                                                         self.config.image_size[2])
        self.image_processed = True
    
    def rovervelCB(self, vel): 
        self.default_speed = vel.linear.x

def main():
    if len(sys.argv) != 3:
        exit('Usage:\n$ rosrun run_neural run_neural.py weight_file_name default_speed(0~1)')

    neural_control = NeuralControl(sys.argv[1], float(sys.argv[2]))
    print('\nStart running. Vroom. Vroom. Vroooooom......')
  
    joy_pub = rospy.Publisher('/rover', Control, queue_size = 10)
    pub4mavros = rospy.Publisher('mavros/setpoint_velocity/cmd_vel_unstamped', Twist, queue_size=20)

    joy_data = Control()
    pub4mavros_data = Twist()
    
    while not rospy.is_shutdown():
        if neural_control.image_processed is False:
            continue
        
        prediction = neural_control.drive.run(neural_control.image)
        joy_data.steer = prediction
        pub4mavros_data.angular.z = prediction*(1+1*0.5)
        joy_data.throttle = neural_control.default_speed
        pub4mavros_data.linear.x = neural_control.default_speed
        joy_pub.publish(joy_data)
        pub4mavros.publish(pub4mavros_data)

        ## print out
        sys.stdout.write('steer: ' + str(joy_data.steer) +' throttle: ' + str(joy_data.throttle) + '\r')
        sys.stdout.flush()

        ## ready for processing a new input image
        neural_control.image_processed = False
        neural_control.rate.sleep()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print ('\nShutdown requested. Exiting...')